config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :dogs
  resources :owners
  resources :walkers
  root 'welcome#index'
  get '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/walker.rb
# == Schema Information
#
# Table name: walkers
#
#  id              :integer          not null, primary key
#  name            :text
#  experience      :text
#  suburbs         :text
#  car             :boolean
#  wage            :text
#  image           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  email           :string
#

class Walker < ActiveRecord::Base
  has_secure_password
  has_many :comments

  # geocoded_by :address
  # after_validation :geocode, :if => :address_changed?
end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController
  before_action :set_walker, only: [:show, :edit, :update, :destroy]
  skip_before_action :fetch_user, :only => [:new, :create]

  # GET /walkers
  def index
    @walkers = Walker.all
  end

  # GET /walkers/1
  def show
      @walker = Walker.find params[:id]
  end

  # GET /walkers/new
  def new
    @walker = Walker.new
  end

  # GET /walkers/1/edit
  def edit
  end

  # POST /walkers
  def create
    @walker = Walker.new(walker_params)
    cloudinary = Cloudinary::Uploader.upload( params[:file] )
    @walker.image = cloudinary["url"]
    # binding.pry
    respond_to do |format|
      if @walker.save
        session[:walker_id] = @walker.id
        session[:owner_id] = nil
        format.html { redirect_to @walker, notice: 'Walker was successfully created.' }
        format.json { render :show, status: :created, location: @walker }
      else
        format.html { render :new }
        format.json { render json: @walker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walkers/1
  def update
    respond_to do |format|
      if @walker.update(walker_params)
        format.html { redirect_to @walker, notice: 'Walker was successfully updated.' }
        format.json { render :show, status: :ok, location: @walker }
      else
        format.html { render :edit }
        format.json { render json: @walker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walkers/1
  def destroy
    @walker.destroy
    respond_to do |format|
      format.html { redirect_to walkers_url, notice: 'Walker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_walker
      @walker = Walker.find(params[:id])
    end
    def walker_params
      params.require(:walker).permit(:name, :email, :experience, :suburbs, :car, :wage, :image, :password, :password_confirmation)
    end
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/views/walkers/_form.html.erb
<%= form_for @walker, :html => { :multipart => true } do |f| %>
  <% if @walker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walker.errors.count, "error") %> prohibited this walker from being saved:</h2>

      <ul>
      <% @walker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <p>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <p>
  <div class="field">
    <%= f.label :experience %>
    <%= f.text_field :experience %>
  </div>
  <p>
  <div class="field">
    <%= f.label :suburbs %>
    <%= f.text_area :suburbs %>
  </div>
  <p>
  <div class="field">
    <%= f.label :car %>
    <%= f.check_box :car %>
  </div>
  <p>
  <div class="field">
    <%= f.label :wage %>
    <%= f.number_field :wage %>
  </div>
  <p>
  <div class="field">
    <%= f.label :image %>
    <%= cl_image_upload_tag :image %>
  </div>
  <p>
  <div class="field">
    <%= f.label :password  %>
    <%= f.password_field :password, :required => true %>
  </div>
  <p>
  <div class="field">
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation, :required => true %>
  </div>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/walkers/edit.html.erb
<h2>Editing Walker</h2>

<%= render 'form' %>

<%= link_to 'Show', @walker %> |
<%= link_to 'Back', walkers_path %>

app/views/walkers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Dog Walkers</h2>

  <body>
    <div class="walkers">
    <% @walkers.each do |walker| %>
      <tr>
        <h3><%= walker.name %></h3>
        <%= image_tag walker.image, :class => 'feature' %>
        <p>
        <td>Email: <%= walker.email %></td>
        <p>
        <td>Experience (yrs): <%= walker.experience %></td>
        <p>
        <td>Located: <%= walker.suburbs %></td>
        <p>
        <td>Has Car: <%= walker.car %></td>
        <p>
        <td>Wage/hr: <%= walker.wage %></td>
        <p>
        <td><strong>Comments: </strong>
          <% walker.comments.each do |comment| %>
          <p></p><%= link_to comment.message, comment %></td>
          <% end %>
      </tr>
    <% end %>
  </div>
  </body>

app/views/walkers/new.html.erb
<h1>New Walker</h1>

<%= render 'form' %>

<%= link_to 'Back', walkers_path %>

app/views/walkers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="walkers">
    <h2><%= @walker.name %></h2>
    <%= image_tag @walker.image, :class => 'feature' %>

    <p>
        <strong>Email:</strong>
        <%= @walker.email %>
    </p>

    <p>
        <strong>Experience:</strong>
        <%= @walker.experience %>
    </p>

    <p>
        <strong>Located:</strong>
        <%= @walker.suburbs %>
    </p>

    <p>
        <strong>Car:</strong>
        <%= @walker.car %>
    </p>

    <p>
        <strong>Wage:</strong>
        <%= @walker.wage %>
    </p>

    <p>
        <strong>Comments:</strong>
        <% @walker.comments.each do |comment| %>
        <p></p><%= link_to comment.message, comment %>
        <% end %>
    </p>

    <%= link_to 'Edit', edit_walker_path(@walker) %>
    |
    <%= link_to 'Back', walkers_path %>
    |
    <%= link_to 'Destroy', @walker, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>