config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :dogs
  resources :owners
  resources :walkers
  root 'welcome#index'
  get '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  author     :string
#  walker_id  :integer
#  owner_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :walker
  belongs_to :owner
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
    @comment = Comment.find params[:id]
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @walkers = Walker.all
    @owners = Owner.all
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)
    @comment.owner = @current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def comment_params
      params.require(:comment).permit(:message, :walker_id, :owner_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %>
        prohibited this comment from being saved:</h2>

    <ul>
        <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
</div>
<p>
    <div class="field">
        <%= f.label :walker_id %><br>
        <%= f.select :walker_id, @walkers.map {|walker| [walker.name, walker.id] } %>
    </div>
    <p>
        <div class="actions">
            <%= f.submit %>
        </div>
        <% end %>

app/views/comments/edit.html.erb
<h2>Editing Comment</h2>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h2>All Comments</h2>

<table>
    <head>
        <tr>
            <th>Owner</th>
            <th>Message</th>
            <th>Walker</th>
            <th colspan="3"></th>
        </tr>
    </head>

    <body>
        <% @comments.each do |comment| %>
        <tr>
            <td><%= comment.walker.name %></td>
            <td><%= comment.message %></td>
            <td><%= comment.owner.name %></td>
            <td><%= link_to 'Show', comment %></td>
            <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
            <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </body>
</table>

<br>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>
<p>
<%= link_to 'Back', walkers_path %>
</p>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="comments">
    <p>
        <strong>Owner:</strong>
        <%= @comment.owner.name %>
    </p>
    <p>
        <strong>Message:</strong>
        <%= @comment.message %>
    </p>

    <p>
        <strong>Walker:</strong>
        <%= @comment.walker.name %>
    </p>

    <%= link_to 'Back', walkers_path %>
</div>