config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :dogs
  resources :owners
  resources :walkers
  root 'welcome#index'
  get '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/owner.rb
# == Schema Information
#
# Table name: owners
#
#  id              :integer          not null, primary key
#  name            :text
#  image           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  email           :string
#

class Owner < ActiveRecord::Base
  has_secure_password
  has_many :dogs
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  skip_before_action :fetch_user, :only => [:new, :create]
  # GET /owners
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  def show
    @owner = Owner.find params[:id]
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  def create
    @owner = Owner.new(owner_params)
    if params[:file].present?
      cloudinary = Cloudinary::Uploader.upload( params[:file] )
      @owner.image = cloudinary["url"]
    end
    respond_to do |format|
      if @owner.save
        session[:owner_id] = @owner.id
        session[:walker_id] = nil
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_owner
      @owner = Owner.find(params[:id])
    end
    def owner_params
      params.require(:owner).permit(:name, :email, :image, :password, :password_confirmation)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= form_for @owner, :html => { :multipart => true } do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true %>
  </div>
  <p>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <p>
  <div class="field">
    <%= f.label :image %><br>
    <%= cl_image_upload_tag :image, :required => true  %>
  </div>
  <p>
  <div class="field">
    <%= f.label :password  %>
    <%= f.password_field :password, :required => true %>
  </div>
  <p>
  <div class="field">
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation, :required => true %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
  </p>
<% end %>

app/views/owners/edit.html.erb
<h2>Editing Owner</h2>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Dog Owners</h2>


  <body>
    <div class="owners">
    <% @owners.each do |owner| %>
      <tr>
        <h3><%= owner.name %></h3>
        <%= image_tag owner.image, :class => 'feature' %>
        <p>
        <td>Email: <%= owner.email %></td>
        <p>
      </tr>
    <% end %>
  </div>
  </body>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<div class="owners">
    <h2><%= @owner.name %></h2>
    <%= image_tag @owner.image, :class => 'feature' %>
    <p>
        <strong>Email: </strong>
        <%= @owner.email %>
    </p>

    <%= link_to 'Edit', edit_owner_path(@owner) %>
    |
    <%= link_to 'Back', owners_path %>
    |
    <%= link_to 'Destroy', @owner, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>