config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :dogs
  resources :owners
  resources :walkers
  root 'welcome#index'
  get '/login' => 'sessions#new', :as => :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => :logout
end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id         :integer          not null, primary key
#  name       :text
#  breed      :text
#  weight     :text
#  suburb     :text
#  concerns   :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  owner_id   :integer
#

class Dog < ActiveRecord::Base
  belongs_to :owner
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  def show
    @dog = Dog.find params[:id]
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
    @owners = Owner.all
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  def create
    @dog = Dog.new(dog_params)
    @dog.owner = @current_user
    unless params[:file].nil?
      cloudinary = Cloudinary::Uploader.upload params[:file]
      @dog.image = cloudinary["url"]
    end

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end

    cloudinary = Cloudinary::Uploader.upload params[:file] if params[:file]
    dog = Dog.find params[:id]
    dog.image = cloudinary["url"] if cloudinary

    dog.update dog_params

    redirect_to dog

  end

  # DELETE /dogs/1
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_dog
      @dog = Dog.find(params[:id])
    end
    def dog_params
      params.require(:dog).permit(:name, :breed, :weight, :suburb, :concerns, :image)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog, :html => { :multipart => true } do |f| %>
<% if @dog.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@dog.errors.count, "error") %>
        prohibited this dog from being saved:</h2>

    <ul>
        <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
</div>
<div class="field">
    <%= f.label :breed %><br>
    <%= f.text_area :breed %>
</div>
<div class="field">
    <%= f.label :weight %><br>
    <%= f.text_area :weight %>
</div>
<div class="field">
    <%= f.label :suburb %><br>
    <%= f.text_area :suburb %>
</div>
<div class="field">
    <%= f.label :concerns %><br>
    <%= f.text_area :concerns %>
</div>
<div class="field">
    <%= f.label :image %><br>
    <%= cl_image_upload_tag :image, :required => true %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/dogs/edit.html.erb
<h2>Editing Dog</h2>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h2>All Dogs</h2>

  <body>
    <div class="dogs">
    <% @dogs.each do |dog| %>
      <tr>
        <h3><%= dog.name %></h3>
        <%= image_tag dog.image, :class => 'feature' %>
        <p>
        <td>Breed: <%= dog.breed %></td>
        <p>
        <td>Located: <%= dog.suburb %></td>
        <p>
        <td>Concerns: <%= dog.concerns %></td>
        <p>
        <td>Owner: <%= link_to dog.owner.name, dog.owner %></td>
        <p>
        <p>
      </tr>
    <% end %>
  </div>
  </body>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h2>New Dog</h2>

<%= render 'form' %>
<p>
<%= link_to 'Back', dogs_path %>
</p>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="dogs">
    <h2><%= @dog.name %></h2>
    <%= image_tag @dog.image, :class => 'feature' %>
    <p>
        <strong>Breed:</strong>
        <%= @dog.breed %>
    </p>

    <p>
        <strong>Weight (kgs):</strong>
        <%= @dog.weight %>
    </p>

    <p>
        <strong>Suburb:</strong>
        <%= @dog.suburb %>
    </p>

    <p>
        <strong>Concerns:</strong>
        <%= @dog.concerns %>
    </p>

    <strong>Owner:</strong>
    <%= link_to @dog.owner.name, @dog.owner %>
    <p>
    <%= link_to 'Edit', edit_dog_path(@dog) %>
    |
    <%= link_to 'Back', dogs_path %>
</div>